# Generated by Django 5.1.3 on 2024-11-10 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado_cita', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en espera', 'En Espera')], default='en espera', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'costos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_diagnostico', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'diagnosticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialesClinicos',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas_generales', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'historiales_clinicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.IntegerField(default=0)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescripciones',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prescripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_resena', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'resena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('permisos', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_tratamiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado_tratamiento', models.CharField(choices=[('finalizado', 'Finalizado'), ('en curso', 'En Curso')], default='en curso', max_length=20)),
            ],
            options={
                'db_table': 'tratamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odontologos',
            fields=[
                ('id_odontologo', models.OneToOneField(db_column='id_odontologo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='odomed.usuario')),
                ('numero_licencia', models.CharField(max_length=50)),
                ('especializacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'odontologos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.OneToOneField(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='odomed.usuario')),
                ('seguro_medico', models.CharField(blank=True, max_length=100, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practicantes',
            fields=[
                ('id_practicante', models.OneToOneField(db_column='id_practicante', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='odomed.usuario')),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_practicas', models.DateField(blank=True, null=True)),
                ('fecha_fin_practicas', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'practicantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recepcionistas',
            fields=[
                ('id_recepcionista', models.OneToOneField(db_column='id_recepcionista', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='odomed.usuario')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recepcionistas',
                'managed': False,
            },
        ),
    ]
